name: Deploy

on:
  push: { branches: ["master"] }

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build to dist
        run: yarn clean && yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: dist
          folder: dist
