name: Metrics
on:
  schedule: [{ cron: "0 0,12,18,22 * * 0-6" }]
  workflow_dispatch:
  push: { branches: ["master"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: header
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          repositories: 200
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          config_timezone: Armenia/Yerevan
          filename: src/assets/images/header.svg
          use_prebuilt_image: yes
      - name: activity & community
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, community
          repositories: 200
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          config_timezone: Armenia/Yerevan
          filename: src/assets/images/activity-community.svg
          use_prebuilt_image: yes
      - name: repositories
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          repositories: 200
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          config_timezone: Armenia/Yerevan
          filename: src/assets/images/repositories.svg
          use_prebuilt_image: yes
          plugin_lines: yes
      - name: recent activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories: 200
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          config_timezone: Armenia/Yerevan
          filename: src/assets/images/recent-activity.svg
          plugin_activity: yes
          plugin_activity_limit: 3
          plugin_activity_days: 0
          plugin_activity_filter: all
      - name: plugin languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories: 200
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          config_timezone: Armenia/Yerevan
          filename: src/assets/images/languages.svg
          use_prebuilt_image: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
      - name: plugin achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories: 200
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          config_timezone: Armenia/Yerevan
          filename: src/assets/images/achievements.svg
          use_prebuilt_image: yes
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
