name: Metrics
on:
  schedule: [{ cron: "0 0,12,18,22 * * 0-6" }]
  workflow_dispatch:
  push: { branches: ["master"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: header
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          repositories: 200
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          config_timezone: Armenia/Yerevan
          filename: images/header.svg
          use_prebuilt_image: yes
      - name: activity & community
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, community
          repositories: 200
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          config_timezone: Armenia/Yerevan
          filename: images/activity-community.svg
          use_prebuilt_image: yes
      - name: repositories
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          repositories: 200
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          config_timezone: Armenia/Yerevan
          filename: images/repositories.svg
          use_prebuilt_image: yes
          plugin_lines: yes
      - name: recent activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories: 200
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          config_timezone: Armenia/Yerevan
          filename: images/recent-activity.svg
          plugin_activity: yes
          plugin_activity_limit: 3
          plugin_activity_days: 0
          plugin_activity_filter: all
      - name: plugin languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories: 200
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          config_timezone: Armenia/Yerevan
          filename: images/languages.svg
          use_prebuilt_image: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
      - name: plugin google page speed
        uses: lowlighter/metrics@latest
        with:
          filename: images/google-page-speed.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://martikavagyan.com

